### ISSUE TITLE
Fix logic for charm publishing workflows for all CI to prevent publishing from forks

### ISSUE THREAD

**Issue by ca-scribner** [canonical/kubeflow-ci#1]
[This PR](https://github.com/canonical/istio-operators/actions/runs/2430012541/attempts/2) from a fork attempted to publish to `ch:istio-pilot/latest/edge/branchname`, but failed because the fork does not have credentials for our charmhub.  On forks, we should skip all publishing entirely (both publish to branch and publish to track/edge) as these forks are not meant to actually feed our main charmhub repos.  Without this change, forks will always have failing CI even if their code works fine

**Comment by beliaev-maksim** [comment]
will be a part of common CI
