### ISSUE TITLE
Fix Check Libraries CI workflow for all repos

### ISSUE THREAD

**Issue by ca-scribner** [canonical/kubeflow-ci#2]
For similar reasons to #1, PRs from forks will fail the check libraries test because the credentials are empty in a fork.

**Comment by ca-scribner** [comment]
This might not be a repeat of #1, but maybe failure just because there are no libraries?  When addressing this, look into the actual cause and don't assume anything :)

**Comment by beliaev-maksim** [comment]
will be a part of common CI
