### ISSUE TITLE
Canon run for flake8 update is required

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/kubeflow-ci#57]
it is required to run a canon run to 
* update all repos flake8 dependency (remove upper boundary)
* update renovate python version to 3.8.10
* update renovate frequency (see https://github.com/canonical/kubeflow-ci/issues/66)

https://github.com/canonical/knative-operators/blob/2e2d833cc98d0b08085302e7619f864cdf0fce9d/requirements-lint.in#L2
https://github.com/canonical/knative-operators/blob/2e2d833cc98d0b08085302e7619f864cdf0fce9d/requirements-lint.in#LL4C1-L4C1

reasoning see here:
https://github.com/canonical/kserve-operators/pull/122#discussion_r1220067170

**Comment by ca-scribner** [comment]
@beliaev-maksim @misohu did we solve this? If so, can we close?
