### ISSUE TITLE
reduce frequency of renovate

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/kubeflow-ci#66]
now renovate fires too many PRs that become extremely noisy, consume GitHub runners and provide low to nothing value

we need to reduce frequency of its runs to once per 2 weeks (that will allow Ticket Guru to merge PRs only once per pulse)

**Comment by beliaev-maksim** [comment]
this might be the solution
https://docs.renovatebot.com/configuration-options/#schedule

**Comment by ca-scribner** [comment]
@beliaev-maksim @misohu did we solve this?  If so, can we close?
