### ISSUE TITLE
fix logdump action to allow using it more than once in the same CI run

### ISSUE THREAD

**Issue by ca-scribner** [canonical/kubeflow-ci#95]
current logdump action dumps artifacts to a hard-coded location.  This means if you run it twice (say once for each of two integration tests), they'll overwrite each other.  Lets make this output configurable, or maybe by default it can introspect the job name (which will be unique) and append it to the output artifact location

**Comment by bschimke95** [comment]
Hi @canonical/kubeflow ,

I recently joined Canonical. One of my on-boarding tasks is to fix a bug in a relevant Canonical project. 

In https://github.com/canonical/kubeflow-ci/pull/111 I propose a fix to make the output location of the log dump configurable. Also, if nothing is set, the action will still fall-back to a unique location facilitating the current job id.
